# Task Object Contract (Internal)
#
# Purpose:
# - Define the minimum interface that any internal task backend must satisfy.
# - Keep queue-layer code independent from a specific backend implementation
#   (for example, callr now, other backends later).
#
# Scope:
# - This is an internal engineering contract, not a user-facing API.
# - `Task` objects are never exported.
#
# -----------------------------------------------------------------------------
# Required Fields
# -----------------------------------------------------------------------------
#
# 1) obj$id
# - Type: character(1)
# - Meaning: stable task identifier generated by taskr (for example "task_001").
#
# 2) obj$created_at
# - Type: POSIXct
# - Meaning: timestamp when the task object is created.
#
# -----------------------------------------------------------------------------
# Required Methods
# -----------------------------------------------------------------------------
#
# 1) obj$status()
# - Return: character(1), one of:
#   - "running"
#   - "done"
#   - "failed"
#   - "killed"
# - Meaning:
#   - "running": task has been launched and not reached a terminal state.
#   - "done": task call finished successfully and expected result is available.
#   - "failed": task call finished with error or subprocess ended unexpectedly.
#   - "killed": task was explicitly cancelled/killed.
#
# 2) obj$is_alive()
# - Return: logical(1)
# - Meaning: whether the underlying process/session is alive.
# - Note: For persistent backends (for example callr::r_session), `is_alive()`
#   may remain TRUE after a single call has already completed.
#
# 3) obj$progress()
# - Return:
#   - NULL if no progress has been received
#   - list(fraction, message, updated_at) otherwise
# - Field expectations:
#   - fraction: numeric(1), expected range [0, 1]
#   - message: NULL or character(1)
#   - updated_at: POSIXct (UTC-compatible timestamp)
#
# 4) obj$read_output()
# - Return: character(1), incremental non-protocol stdout text since last read.
# - Side effect:
#   - Parses embedded taskr progress protocol lines and updates `obj$progress()`.
#   - Appends ordinary stdout to an internal buffer.
#
# 5) obj$read_error()
# - Return: character(1), incremental stderr text since last read.
# - Side effect:
#   - Appends stderr text to an internal buffer.
#
# 6) obj$kill()
# - Return: invisible(self) (or equivalent side-effect-only behavior).
# - Requirement:
#   - Idempotent: repeated calls should not error.
#   - Must transition task status to "killed".
#
# 7) obj$elapsed()
# - Return: numeric(1) seconds (or difftime coercible to numeric seconds).
# - Meaning: elapsed wall-clock time from creation to now/finish.
#
# -----------------------------------------------------------------------------
# Result Channel Contract
# -----------------------------------------------------------------------------
#
# - Task results are NOT returned through a direct task method.
# - Child code writes result objects to taskr-managed temp files.
# - Queue/user layers resolve result paths and read files separately.
#
# -----------------------------------------------------------------------------
# Error Contract
# -----------------------------------------------------------------------------
#
# - Failed tasks must expose a readable failure message, ideally preserving the
#   original child error message when available.
# - If child details are unavailable, use a fallback like
#   "subprocess died unexpectedly".
#
# -----------------------------------------------------------------------------
# Backend Compatibility Notes
# -----------------------------------------------------------------------------
#
# - Queue layer must only depend on this contract, never on backend-specific
#   methods such as `callr::*`.
# - Backend adapters may keep extra internal fields/methods, but they must not
#   break the required fields/methods above.
